artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://archive.ics.uci.edu/ml/machine-learning-databases/00222/bank.zip
  local_data_file: artifacts/data_ingestion/bank.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion/bank-full.csv
  STATUS_FILE: artifacts/data_validation/status.yaml

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/bank-full.csv
